server:
  port: 8080
# ЭТО PROD
lock:
  watchdog-timeout: 30000
  single-server-config:
    address: "redis://redis:6379"
    password: ${SPRING_REDIS_PASSWORD}
    connection-pool-size: 64
# ЭТО PROD
spring:
  # Включение цветового вывода (даже если терминал не определяется автоматически)
  output:
    ansi:
      enabled: ALWAYS
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: ${SCHEMA:game} # Значение по умолчанию, если переменная окружения не задана
    parameters:
      # Опциональные параметры для changelog-файлов, если они используются
      exampleParameter: value
  data:
    redis:
      host: redis
      port: 6379
      password: ${SPRING_REDIS_PASSWORD}
      database: 0
  main:
    allow-circular-references: true
  application:
    name: creazione
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
# ЭТО PROD
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
      default_batch_fetch_size: 20
      generate_statistics: true
    properties:
      hibernate:
        default_schema: ${SCHEMA}
        jdbc:
          lob:
            non_contextual_creation: true

bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}
  channel:
    id:
# ЭТО PROD
# Настройка уровней логирования
logging:
  level:
    root: INFO
    com.creazione: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"  # Стандартный паттерн с цветами:cite[4]

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: ${SCHEMA}
    liquibase-schema: ${SCHEMA}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
    enabled-by-default: true
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true