-- V2__alter_scheduler_table.sql
ALTER TABLE scheduler
ALTER COLUMN last_start TYPE TIMESTAMP WITH TIME ZONE USING last_start AT TIME ZONE 'UTC';

ALTER TABLE scheduler
ALTER COLUMN previous_start TYPE TIMESTAMP WITH TIME ZONE USING previous_start AT TIME ZONE 'UTC';

ALTER TABLE scheduler
ALTER COLUMN last_end TYPE TIMESTAMP WITH TIME ZONE USING last_end AT TIME ZONE 'UTC';

ALTER TABLE scheduler
ALTER COLUMN previous_end TYPE TIMESTAMP WITH TIME ZONE USING previous_end AT TIME ZONE 'UTC';