#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $APP_DB_USER WITH PASSWORD '$APP_DB_PASSWORD';
    CREATE DATABASE $APP_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $APP_DB_NAME TO $APP_DB_USER;

    \c $APP_DB_NAME;
    CREATE SCHEMA IF NOT EXISTS $SCHEMA;
    GRANT ALL PRIVILEGES ON SCHEMA $SCHEMA TO $APP_DB_USER;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA $SCHEMA TO $APP_DB_USER;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA $SCHEMA TO $APP_DB_USER;
    ALTER USER $APP_DB_USER SET search_path TO $SCHEMA;

    -- Даем права на создание таблиц в схеме
    GRANT CREATE ON SCHEMA $SCHEMA TO $APP_DB_USER;
EOSQL